python ../inference_shape_seg.py \
    --output_dir='/nas/users/dahye/save_pretrained/inference/airplane_shape_seg' \
    --height=64 \
    --width=64 \
    --segment_data_test_dir='/nas/users/dahye/dataset/lsun/one_obj_64/airplane/test' \
    --trained_ckpt_path='/nas/users/dahye/mygit/shape-gan-seg/pretrained_v1/lsun_airplane/trained_model_by_best_val_iou.pth' \
    --num_in_channel=3 \
    --num_out_channel=3 \
    --test_batch_size=128 \
    --num_workers=16 \
    --multi_gpu=False \
    --num_gpu=1 \
    --cuda_id='cuda:0';